steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/pailsom-db-gcp/flare-batch:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/pailsom-db-gcp/flare-batch"]